default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: code-challange
  password: password
  pool: 5

development:
  <<: *default
  database: code-challenge_development


test:
  <<: *default
  database: code-challenge_test
