env:
  RUBY_VERSION: 2.5.5
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

name: Rails tests
on: [push,pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - run: bundle exec rake
      # - name: Install Rubocop
      #   run: gem install rubocop
      - name: Check code
        run: rubocop
  rspec-test:
    name: RSpec
    needs: rubocop-test
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - run: bundle exec rake
      # - name: Install dependencies
      #   run: |
      #     gem install bundler
      #     bundler install
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake